name: Run find_lowest_number test
on: [push]
jobs: 
  test-find-lowest:
    runs-on: ubuntu-latest
    name: Test find_lowest_number
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
    - uses: actions/setup-python@v3
    - with:
        python-version: '3.10'

    - name: Ten Numbers
    - run: python find_lowest_number.py > test1_input.txt 
    - name: Compare outputs 1
    - run: diff test1_input.txt test1_expected.txt

    - name: One number
    - run: python find_lowest_number.py > test2_input.txt 
    - name: Compare outputs 1
    - run: diff test2_input.txt test2_expected.txt

    - name: No numbers
    - run: python find_lowest_number.py > test3_input.txt 
    - name: Compare outputs 1
    - run: diff test3_input.txt test3_expected.txt
    
  
  
